name: CI/CD Pipeline for Flask App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Use Python 3.10 to match Dockerfile

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt  # Correct path to the file

    - name: Build Docker Image
      run: docker build -t flask-cicd-app .

    - name: Test Application (Optional)
      run: echo "Run your tests here"

    - name: Deploy (Optional)
      run: echo "Deploy to your environment"
